# From https://github.com/actions-rs/meta/blob/master/recipes/msrv.md
on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    strategy:
      matrix:
        rust:
          - stable
          - 1.41.1
          - nightly
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    strategy:
      matrix:
        rust:
          - stable
          - 1.41.1
          - nightly
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  bench:
    name: Benchmark
    strategy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-07-05
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench --features bench
